# Generated by Django 4.0.5 on 2022-06-25 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('!', 'WAITING'), ('!!', 'TODO'), ('!!!', 'URGENT')], default='!', max_length=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=300)),
                ('due_date', models.DateTimeField(null=True)),
                ('complete', models.BooleanField(default='False')),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmaster.todolist')),
            ],
        ),
    ]
